language: bash
services:
  - docker
script:
  - docker-compose up -d
  - docker-compose ps
  - sleep 120
  - docker-compose ps
  - docker logs node1
  - bash ./travis-ci/create_gr.sh
  - sleep 30
  - bash ./travis-ci/test_gr.sh
after_script:
  - docker-compose down

