scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['10.0.2.2:9100']

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
